@baseUrl = http://localhost:3000
# @baseUrl = https://endava.azurewebsites.net
###
GET {{baseUrl}}
Authorization: Bearer {{token}}

### Health and readiness endpoints
GET {{baseUrl}}/health
###
GET {{baseUrl}}/ready
###
GET {{baseUrl}}/certificates
###
GET {{baseUrl}}/certificates?vendor=Azure
###
GET {{baseUrl}}/certificates?vendor=AWS
###
GET {{baseUrl}}/certificates/roles
###
GET {{baseUrl}}/certificates?role=DevOps Engineer
###
POST {{baseUrl}}/certificates
