CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE certificate_vendor AS ENUM (
    'Azure',
    'AWS'
);

CREATE TYPE certificate_level AS ENUM (
    'Associate',
    'Professional'
);

CREATE TABLE user_roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text NOT NULL
);

INSERT INTO user_roles (id, name, description)
VALUES (1, 'user', 'Default user role');

CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    entra_object_id text NOT NULL UNIQUE,
    email text NOT NULL,
    display_name text NOT NULL,
    role_id integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES user_roles (id)
);

CREATE TABLE certificates (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor certificate_vendor NOT NULL,
    code text,
    name text NOT NULL,
    description text NOT NULL,
    badge_url text NOT NULL,
    level certificate_level NOT NULL,
    role text NOT NULL,
    subject text NOT NULL,
    external_link text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

CREATE INDEX IF NOT EXISTS idx_certifications_vendor ON certificates (vendor);
CREATE INDEX IF NOT EXISTS idx_certifications_level ON certificates (level);
CREATE INDEX IF NOT EXISTS idx_certifications_name ON certificates (name);
